### ISSUE TITLE
incorrect download for triton model with non-empty config.pbtxt

### ISSUE THREAD

**Issue by dumbPy** [kserve/modelmesh-runtime-adapter#25]
[modelmesh-serving's model-types/advanced-configuration.md](https://github.com/kserve/modelmesh-serving/blob/54311bb26ec9e8f6176538ec9224afbb61f94d0a/docs/model-types/advanced-configuration.md) shows this is suppose to work as expected, but doesn't seem to for me.

## The Problem
For Triton, a model directory consists of atleast 2 files (in most cases) that need to be pulled.  
```
models
└── coco-onnx
    ├── 1
    │   └── model.onnx
    └── config.pbtxt
```
Here, if we provide Predictor's `storage.path: 's3://models/coco-onnx'` it would puts the coco-onnx model inside modelId dir
```
/models                                             #<-- model root
└── yolo-onnx__ksp-f3a4aa93aa                       #<-- modelId
    └── coco-onnx
        ├── 1
        │   └── model.onnx
        └── config.pbtxt
```
which the triton cannot load, since it expects it to be
```
/models
└── yolo-onnx__ksp-f3a4aa93aa
    ├── 1
    │   └── model.onnx
    └── config.pbtxt
```
instead.

## Expected Solution
When the `storage.path` is pointing to a model folder, that has `config.pbtxt` in it, the contents of it should be copied inside `<modelId>` folder (eg. yolo-onnx__ksp-f3a4aa93aa) instead of the `<modelId>/<modelName>` folder. 

## config.pbtxt used
```
name: "coco-onnx"
max_batch_size:4
optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP32" }
    parameters { key: "max_workspace_size_bytes" value: "1073741824" }}
  ]
}}
input [
  {
    name: "input"
    data_type: TYPE_UINT8
    dims: [ 3 , -1, -1]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  },
]

```
## Predictor definition used
```
kubectl apply -f - <<EOF
apiVersion: serving.kserve.io/v1alpha1
kind: Predictor
metadata:
  name: yolo-onnx
spec:
  modelType:
    name: custom                   #<-- custom since I was trying to see if putting onnx was the issue. neither works
  runtime:
    name: triton-2.x
  path: triton-yolo-models/coco-onnx
  storage:
    s3:
      secretKey: localMinIO
      bucket: triton-models
EOF
```

**Comment by tjohnson31415** [comment]
Hello @dumbPy. Thanks for the detailed report!

I double checked that the advanced configuration layout still works with the built in Triton runtime for me. I walk through how that is meant to work below.
I did this test using a model that is included in the `kserve/modelmesh-minio-dev-examples` minio image [that is used for the FVTs](https://github.com/kserve/modelmesh-serving/blob/6bdc38d75c0e7c18716f94a75fb2318110bf87f7/config/dependencies/fvt.yaml#L93). Assuming you installed with the quick-start, you can recreate the minio pod with that image and test with the following predictor:
```
apiVersion: serving.kserve.io/v1alpha1
kind: Predictor
metadata:
  name: test-issue-25
spec:
  modelType:
    name: onnx
  path: fvt/onnx/onnx-test-model
  storage:
    s3:
      secretKey: localMinIO
```

This test model has the following structure in minio:
```
onnx-test-model
        ├── 1
        │   └── model.onnx
        ├── test_labels.txt
        └── config.pbtxt
 ```
 
 When the Puller downloads the model, it keeps the `onnx-test-model` directory in the `/models` volume in a similar structure to your predictor:
 ```
/models
└── test-issue-25__ksp-09fa631dda
    └──onnx-test-model
        ├── 1
        │   └── model.onnx
        ├── test_labels.txt
        └── config.pbtxt
```

In the built-in Triton runtime, we include the [built-in adapter](https://github.com/kserve/modelmesh-serving/blob/6bdc38d75c0e7c18716f94a75fb2318110bf87f7/config/runtimes/triton-2.x.yaml#L89-L93) to help with transforming these files into something that Triton can load. The transformed files are placed in `/models/_triton_models` which is where Triton will load from. This transformation includes "removing" the `onnx-test-model` directory such that the resulting structure is:
```
/models/_triton_models
└── test-issue-25__ksp-09fa631dda
    ├── 1
    │   └── model.onnx
    ├── test_labels.txt
    └── config.pbtxt
```
which Triton is able to load with the generated model id that ModelMesh expects.

---

So that is how it is supposed to work with a Triton model that includes `config.pbtxt`. Note that this relies on the built-in adapter in the provided `triton-2.x` runtime to adapt the file structures in the way you described.

I'm not sure why your Predictor is failing. Because the files in `/models` are removed after the load fails, it can be difficult to debug this kind of failure. That said, there should be additional information about the model load failure in the "Last Failure Info" section of the output of `kubectl describe predictor yolo-onnx`. There may also be some info in the `triton-adapter` and/or `triton` container logs in the runtime pod that could help with debugging. Please check in those places and post any relevant info you find.
