### ISSUE TITLE
v0.11.0: Model directory creation and loading error

### ISSUE THREAD

**Issue by RobGeada** [kserve/modelmesh-runtime-adapter#41]
Model loading fails with the v0.11 images where the model uses a HTTP protocol storageUri:

Error message:
`Failed to create model directory and load model {"modelId":  $model_name, "error": "Error calling stat on /models/$model_name__isvc-xxx/. : start /models/$model_name/... not a directory"`

Downgrading to the v0.10 image eliminates the problem.

**Comment by ckadner** [comment]
do you have an examples model / ISVC and how you deployed it -- I'm curious why it says `$model_name` in the error message

**Comment by ckadner** [comment]
Thanks Rob. And you deployed a ISVC like this?

```YAML
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-sklearn-isvc
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: mlserver-0.x
      storageUri: "https://github.com/trustyai-explainability/trustyai-explainability/raw/main/explainability-service/demo/models/model.joblib?raw=true"
```

And the same `storageUri` worked in `v0.10.0`?
